name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_docker_images:
    name: Build Docker Image To Dockerhub
    runs-on: [ubuntu-latest]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set TAG env
        run: echo "TAG=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: test TAG
        run: echo ${TAG}

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DH_REPO_NAME}}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true

      - name: Build And Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DH_REPO_NAME}}:${{ env.TAG }}

      - name: Update k8s values with new image tag
        run: |
          sed -i "s/tag: .*/tag: ${TAG}/" shop-points-helm/values.yaml

      - name: Commit and push updated values file
        uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        with:
          commit_message: "Update image tag to ${{ env.TAG }}"
