name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_docker_images:
    name: Build Docker Image To Dockerhub
    runs-on: [ubuntu-latest]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set TAG env
        run: echo "TAG=$(date 'YYYYMMDD-hhmmss')" >> $GITHUB_ENV

      - name: test TAG
        run: echo ${TAG}

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DH_REPO_NAME}}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true

      - name: Build And Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: '${{ env.TAG }}'

      - name: Update k8s values with new image tag
        run: |
          sed -i "s/image: jsuarezm\/shop-points:.*/image: jsuarezm\/shop-points:${TAG}/" k8s/app.yaml

      - name: Commit and push updated values file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/app.yaml
          git commit -m "Update image tag to $TAG"
          git push
